version: "2"
services:
  app:
    container_name: "tourism_app"
    image: "pglu/tourism-cpanel"
    build: .
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./public/downloads:/var/www/html/public/downloads
      - ./public/images:/var/www/html/public/images
      - ./public/uploads:/var/www/html/public/uploads
      - ./logs:/var/www/html/logs
    environment:
      - "DATABASE_HOST=database"
      - "DATABASE_TARGET=tourism"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=Xv&kV!pe6Bwa-#h^"
      - "UPLOAD_PATH=/var/www/html/public/uploads"
      - "CSV_GENERATION_PATH=/var/www/html/public/downloads"
      - "CSV_HTTP_PATH=/downloads"
      - "USE_LOCAL_FILESYSTEM=1"
      - "DISPLAY_ERROR_DETAILS=1"
      - "IMGUR_URL=https://api.imgur.com/3/image"
      - "IMGUR_CLIENT_ID=013b73a127469db"
      - "IMGUR_ACCESS_TOKEN=6ae45baa5d6ce314a208231c7857519590f4ab3b"
      - "IMGURL_REFRESH_TOKEN=4b3cdc2d7208afa04ea1f81a92446c2a8b266b3e"
    ports:
      - '80:80'
    links:
      - db:database
    depends_on:
      - db
    restart: always
  db:
    container_name: "tourism_db"
    image: "mysql:5.7"
    volumes:
      - tourism_db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=Xv&kV!pe6Bwa-#h^"
      - "MYSQL_DATABASE=tourism"
      - "TZ=Asia/Manila"
    restart: always
volumes:
  tourism_db: