version: "2"
services:
  cpanel:
    container_name: "tourism_cpanel"
    image: "pglu/tourism-cpanel"
    build: .
    working_dir: /var/www/html
    volumes:
      - ./cpanel/src:/var/www/html/cpanel/src
      - ./cpanel/templates:/var/www/html/cpanel/templates
      - ./cpanel/public/css:/var/www/html/cpanel/public/css
      - ./cpanel/public/js:/var/www/html/cpanel/public/js
      - tourism_cpanel_logs:/var/www/html/cpanel/logs
    ports:
      - '80:80'
    links:
      - db:database
    depends_on:
      - db
  db:
    container_name: "tourism_db"
    image: "mysql:5.7"
    volumes:
      - tourism_db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=Xv&kV!pe6Bwa-#h^"
      - "TZ=Asia/Manila"
volumes:
  tourism_db:
  tourism_cpanel_logs: