<?php if($imageCount == 0): ?>
    <div class="card-panel amber darken-4">
        <span style="font-weight: bold">No images available.</span>
    </div>
<?php else: ?>
    <div class="owl-carousel owl-theme">
        <?php if(strlen($imageSrc) > 0): ?>
            <img data-src="<?= $imageSrc ?>" alt="" class="owl-lazy responsive">
        <?php endif; ?>
        <?php foreach($images as $image): ?>
            <img data-src="<?= $image ?>" alt="" class="owl-lazy responsive">
        <?php endforeach; ?>
    </div>
    <?php if(strlen(trim($poi['photoCredit']))): ?>
        <span style="font-weight: bold">
            Images by:&nbsp;
        </span>
        <ul class="browser-default">
            <?php foreach(explode(',', $poi['photoCredit']) as $photoCredit): ?>
                <li><?= $photoCredit ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>

<?php if (strlen(trim($poi['videoLink']))): ?>
    <span style="font-weight: bold; display: block; margin-top: 50px">
        <?php if(strlen(trim($poi['videoCredit']))): ?>
            Video by:&nbsp;
            <ul class="browser-default">
                <?php foreach(explode(',', $poi['videoCredit']) as $photoCredit): ?>
                    <li><?= $photoCredit ?></li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            Video
        <?php endif; ?>
    </span>
    <a href="<?= $poi['videoLink'] ?>" class="btn blue ligthen-1" target="_blank">Show Video</a>
<?php endif;?>

