<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<div class="section">
    <h5>Manage Fees</h5>
</div>
<form method="post" action="<?= $url ?>">
    <div class="input-field">
        <label>Description</label>
        <input type="text" name="description" <?= $updateMode ? "value=\"{$fee['description']}\"" : "" ?> />
    </div>
    <div class="row">
        <div class="col l3">
            <h6>Free Admission</h6>
            <div class="switch">
                <label>
                    No
                    <input type="checkbox" name="freePrice" <?= $updateMode ? ($fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "checked" : "") : "" ?>>
                    <span class="lever"></span>
                    Yes
                </label>
            </div>
        </div>
        <div class="col l9">
            <div class="input-field">
                <input type="number" name="amount" step=".01" <?= $updateMode ? "value=\"{$fee['amount']}\"" : "" ?> />
                <label>Price</label>
            </div>
            <?php if ($updateMode) : ?>
                <div>
                    <h6>Enable Fee</h6>
                    <div class="switch">
                        <label>
                            No
                            <input type="checkbox" name="enabled" <?= $updateMode ? ($fee['enabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "checked" : "") : "" ?>>
                            <span class="lever"></span>
                            Yes
                        </label>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <input type="hidden" name="poi" value="<?= $poi ?>" />
    <?php if ($updateMode) : ?>
        <input type="hidden" name="id" value="<?= $fee['id'] ?>" />
    <?php endif; ?>
    <button class="btn waves-effect waves-light" type="submit" name="action">Add<i class="material-icons left">add</i></button>
</form>
<table class="striped">
    <thead>
        <tr>
            <th>Name</th>
            <td colspan="3"><?= $name ?></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th style="width: 35%">Description</th>
            <th style="width: 30%">Price</th>
            <th style="width: 10%">Enabled</th>
            <th style="width: 15%">Actions</th>
        </tr>
        <?php foreach ($fees as $fee) : ?>
            <tr>
                <td><?= $fee['description'] ?></td>
                <td><?= $fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Free Admission" : "PHP " . number_format($fee['amount'], 2) ?></td>
                <td><?= $fee['enabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Yes" : "No" ?></td>
                <td>
                    <a href="<?= "/cpanel/fee/{$fee['id']}" ?>"><i class="material-icons left">edit</i></a>
                    <a id="remove-<?= $fee['id'] ?>" href="#" data-target="removeFee" class="modal-trigger"><i class="material-icons left">delete</i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="removeFee" class="modal">
    <div class="modal-content">
        <h4>Do you want to remove this schedule ?</h4>
        <table>
            <tbody>
                <tr>
                    <th style="width: 25%">Description</th>
                    <td id="description"></td>
                </tr>
                <tr>
                    <th>Amount</th>
                    <td id="amount"></td>
                </tr>
            </tbody>
        </table>
        <input type="hidden" id="feeId" />
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-light btn green lighten-1">No</a>
        <a href="#!" class="modal-close waves-effect waves-light btn red lighten-1" id="continueRemove">Yes</a>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        <?php if (isset($notification)) : ?>
            M.toast({
                html: '<?= $notification ?>'
            });
        <?php endif; ?>

        $("[name=freePrice]").change(function() {
            $("[name=amount]").prop('disabled', $(this).is(':checked'));
            $("[name=amount]").val(null);
        });

        $('.modal').modal({
            onOpenStart: function(e, t) {
                let entries = t.id.split("-");
                let id = entries[1];
                $.ajax({
                    url: `/api/fee/${id}`,
                    method: 'GET',
                }).done(function(data, status, xhr) {
                    $("#feeId").val(data.id);
                    $("#description").html(data.description);
                    $("#amount").html(data.amount);
                }).fail(function(xhr, status, err) {
                    console.error(err);
                    throw err;
                });
            }
        });

        $('#continueRemove').click(function() {
            let id = $("#feeId").val();
            $.ajax({
                url: `/api/fee/${id}`,
                method: 'DELETE',
                data: {
                    poi: <?= $id?>
                }
            }).done(function(data, status, xhr) {
                window.location = data.url;
            }).fail(function(xhr, status, err) {
                console.error(err);
                window.location = `/cpanel/poi/<?= $id?>/fees`
            });
        });
    });
</script>