<footer class="page-footer grey">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <img src="/images/elyuturismo-logo.png" style="width: 152px; height: 152px;"/>
                <p class="grey-text text-lighten-4">Description</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="/about">About</a></li>
                    <li><a class="grey-text text-lighten-3" href="/privacy">Privacy and Usage Policy</a></li>
                    <li><a class="grey-text text-lighten-3" href="https://launion.gov.ph/">Provincial Government of La Union</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            &copy; <?php echo date('Y') ?> Copyright
        </div>
    </div>
</footer>