<div class="row">
    <h5 class="flow-text center">Visitor Count per Town</h5>
    <canvas id="visitorCountChart" width="400" height="200"></canvas>
</div>

<div class="row">
    <h5 class="flow-text center">Destination Ranking</h5>
    <?php if (count($destinations) == 0) : ?>
        <div class="card-panel red lighten-2">
            <strong class="flow-text white-text">No Available Data</strong>
        </div>
    <?php else: ?>
        <table class="striped" id="ranks">
            <thead>
                <tr>
                    <th class="center" style="width: 10%">Rank</th>
                    <th class="center" style="width: 40%">Tourist Destination</th>
                    <th class="center" style="width: 15%">Town</th>
                    <th class="center" style="width: 15%">Tourism Circuit</th>
                    <th class="center" style="width: 20%">Total Count</th>
                </tr>
            </thead>
            <tbody>
                <?php $count = 1;?>
                <?php foreach($destinations as $destination): ?>
                    <tr>
                        <td class="center"><?= $count;?></td>
                        <td><?= $destination['name']; ?></td>
                        <td><?= $destination['town']; ?></td>
                        <td><?= $destination['tourismCircuit']; ?></td>
                        <td class="center"><?= $destination['visitorCount'];?></td>
                    </tr>
                    <?php $count++; ?>
                <?php endforeach;?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>

<?php $maxCount+=100; ?>
<script>
    var ctx = document.getElementById('visitorCountChart');
    var myChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: <?= $towns ?>,
            datasets: [{
                label: 'Number of Visitors',
                backgroundColor: [
                    'rgba(54, 39, 8, 1)', //agoo
                    'rgba(1, 113, 133, 1)', //aringay
                    'rgba(251, 135, 0, 1)', //bacnotan
                    'rgba(203, 15, 4, 1)', //bagulin
                    'rgba(71, 34, 7, 1)', //balaoan
                    'rgba(189, 72, 88, 1)', //bangar
                    'rgba(55, 104, 39, 1)', //bauang
                    'rgba(7, 135, 16, 1)', //burgos
                    'rgba(241, 167, 18, 1)', //caba
                    'rgba(77, 77, 77, 1)', //luna
                    'rgba(94, 45, 49, 1)', //naguilian
                    'rgba(0, 91, 152, 1)', //pugo
                    'rgba(162, 80, 20, 1)', //rosario
                    'rgba(255, 1, 0, 1)', //san fernando
                    'rgba(69, 122, 236, 1)', //san gabriel
                    'rgba(5, 98, 255, 1)', //san juan
                    'rgba(141, 71, 37, 1)', //santo tomas
                    'rgba(68, 127, 17, 1)', //santol
                    'rgba(6, 70, 20, 1)', //sudipen
                    'rgba(2, 187, 0, 1)' //tubao
                ],
                data: <?= $inputData ?>
            }]
        },
        options: {
            scales: {
                xAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: <?= floor($maxCount * 0.25) ?>,
                        suggestedMin: 0,
                        suggestedMax: <?= $maxCount ?>
                    }
                }]
            }
        }
    });

    $(document).ready(function() {
        $("#ranks").jqxDataTable({
            width: '100%',
            theme: 'material',
            filterable: true,
            selectionMode: 'singleRow',
            pageable: true,
            pagerMode: 'advanced',
            pageSizeOptions: ['10', '50', '100'],
            altRows: true,
            sortable: true,
            columns: [
                { 
                    text: 'Rank', 
                    dataField: 'Rank', 
                    width: '10%',
                    align: 'center',
                    cellsAlign: 'center',
                    cellsRenderer: function(row, column, value, rowData) {
                        return `<span style="display: block; font-weight: bold;">${value}</span>`
                    }
                },
                { 
                    text: 'Tourist Destination', 
                    dataField: 'Tourist Destination',
                    align: 'center',
                    cellsAlign: 'left',
                    width: '40%',
                },
                { 
                    text: 'Tourism Circuit', 
                    dataField: 'Tourism Circuit',
                    align: 'center',
                    cellsAlign: 'left',
                    width: '15%',
                },
                { 
                    text: 'Town', 
                    dataField: 'Town',
                    align: 'center',
                    cellsAlign: 'left',
                    width: '15%',
                },
                { 
                    text: 'Total Count', 
                    dataField: 'Total Count', 
                    width: '20%',
                    align: 'center',
                    cellsAlign: 'center'
                }
            ]
        });
    });
</script>