<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
        <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
        <style type="text/css">
            .ql-editor strong {
                font-weight:bold;
            }
        </style>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
        <title>PGLU Tourism Control Panel</title>
    </head>

    <body>
        <?php include_once 'navigation.phtml'; ?>

        <div class="container hide-on-med-and-down">
            <div class="row" style="margin-top: 30px;">
                <div class="col l3">
                    <div class="collection">
                        <a href="<?= "/cpanel/poi/{$id}" ?>" class="collection-item">Basic Info</a>
                        <a href="<?= "/cpanel/poi/{$id}/schedules" ?>" class="collection-item">Schedules</a>
                        <a href="<?= "/cpanel/poi/{$id}/fees" ?>" class="collection-item">Fees</a>
                        <a href="<?= "/cpanel/poi/{$id}/contacts" ?>" class="collection-item">Contact Details</a>
                        <a href="<?= "/cpanel/poi/{$id}/admin" ?>" class="collection-item">Controls</a>
                        <a href="#" class="collection-item red lighten-1 white-text"><i class="material-icons right">warning</i>Remove</a>
                    </div>
                </div>
                <div class="col l9">
                    <?=$content?>
                </div>
            </div>
        </div>
        <div class="container hide-on-large-only">
            <div class="row" style="margin-top: 20px;">
                <div class="center">
                    <i class="material-icons center large">mobile_off</i>
                    <p>Oops! You are attempting to view a site that is not compatible for mobile and tablet devices.</p>
                </div>
            </div>
        </div>

        <?php include_once 'footer.phtml'; ?>
    </body>
</html>