<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/jqx.base.css" />
        <link rel="stylesheet" href="/assets/css/jqx.material.css" />
        <link rel="stylesheet" href="https://unpkg.com/materialize-stepper@3.1.0/dist/css/mstepper.min.css">
        <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
        <link href="/assets/css/cpanel.css" rel="stylesheet"/>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="/assets/js/jqx-all.js"></script>
        <script src="https://unpkg.com/materialize-stepper@3.1.0/dist/js/mstepper.min.js"></script>
        <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
        <title>ELYU Turismo System Management</title>
    </head>

    <body>
        <?php include_once 'navigation.phtml'; ?>

        <div class="container hide-on-med-and-down">
            <?= $content ?>
        </div>

        <div class="hide-on-med-and-down">
            <?php include_once 'footer.phtml'; ?>
        </div>

        <div class="container hide-on-large-only">
            <div class="row" style="margin-top: 20px;">
                <div class="center">
                    <i class="material-icons center large">mobile_off</i>
                    <p>Oops! You are attempting to view a site that is not compatible for mobile and tablet devices.</p>
                </div>
            </div>
        </div>
    </body>
</html>