<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
        <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
        <style type="text/css">
            .ql-editor strong {
                font-weight: bold;
            }
        </style>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <title>ELYU Turismo System Management</title>
    </head>

    <body>
        <?php include_once 'navigation.phtml'; ?>
        <div class="container hide-on-med-and-down">
            <div class="row" style="margin-top: 30px;">
                <div class="col l3">
                    <div class="collection">
                        <a href="<?= "/cpanel/poi/{$id}" ?>" class="collection-item">Basic Info</a>
                        <a href="<?= "/cpanel/poi/{$id}/schedules" ?>" class="collection-item">Schedules</a>
                        <a href="<?= "/cpanel/poi/{$id}/fees" ?>" class="collection-item">Fees</a>
                        <a href="<?= "/cpanel/poi/{$id}/contacts" ?>" class="collection-item">Contact Details</a>
                        <a href="<?= "/cpanel/poi/{$id}/admin" ?>" class="collection-item">Controls</a>
                        <a href="#" class="collection-item red lighten-1 white-text modal-trigger" data-target="removeDestination" id=<?= "removeDestination-{$id}" ?>><i class="material-icons right">warning</i>Remove</a>
                    </div>
                    <div id="removeDestination" class="modal">
                        <div class="modal-content">
                            <h4>Do you want to remove this Tourist Destination ?</h4>
                            <input type="hidden" id="enrichmentPoiId" />
                        </div>
                        <div class="modal-footer">
                            <a href="#!" class="modal-close waves-effect waves-light btn green lighten-1">No</a>
                            <a href="#!" class="modal-close waves-effect waves-light btn red lighten-1" id="proceedDestinationRemoval">Yes</a>
                        </div>
                    </div>
                    <script>
                        $(document).ready(function() {
                            $('#removeDestination').modal({
                                onOpenStart: function(e, t) {
                                    let entries = t.id.split("-");
                                    let id = entries[1];
                                    $("#enrichmentPoiId").val(id);
                                }
                            });

                            $("#proceedDestinationRemoval").click(function() {
                                let id = $("#enrichmentPoiId").val();
                                $.ajax({
                                    url: `/api/poi/${id}`,
                                    method: 'DELETE'
                                }).done(function(data, status, xhr) {
                                    window.location = `/cpanel/poi`
                                }).fail(function(xhr, status, err) {
                                    console.error(err);
                                    window.location = `/cpanel/poi`
                                });
                            });
                        });
                    </script>
                </div>
                <div class="col l9">
                    <?= $content ?>
                </div>
            </div>
        </div>
        <div class="container hide-on-large-only">
            <div class="row" style="margin-top: 20px;">
                <div class="center">
                    <i class="material-icons center large">mobile_off</i>
                    <p>Oops! You are attempting to view a site that is not compatible for mobile and tablet devices.</p>
                </div>
            </div>
        </div>
        <?php include_once 'footer.phtml'; ?>
    </body>
</html>