<div class="navbar-fixed">
    <nav class="indigo darken-4">
        <div class="nav-wrapper container">
            <a href="/cpanel" class="brand-logo">PGLU Tourism Control Panel</a>
            <ul class="right hide-on-med-and-down">
                <li><a href="/cpanel/poi">Points of Interest</a></li>
                <li><a href="/cpanel/discovery">Suggestions</a></li>
                <li>
                    <a class="dropdown-trigger" href="#!" data-target="settingsDropdown">Settings<i class="material-icons right">arrow_drop_down</i></a>
                    <ul id="settingsDropdown" class="dropdown-content">
                        <li><a href="/cpanel/tags">Tags</a></li>
                        <li class="divider">&nbsp;</li>
                        <li><a href="/cpanel/classifications">Tourist Area Classification</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $(".dropdown-trigger").dropdown({
            hover: false
        });
    });
</script>