<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<h6 style="margin-bottom: 30px;">Manage Products</h6>
<form method="post" action="<?= $url ?>" enctype="multipart/form-data">
    <div class="input-field">
        <input name="town" type="text" value="<?= $town ?>" readonly />
        <label>Town</label>
    </div>
    <div class="input-field">
        <input name="name" type="text" class="validate" required value="<?= $product['name'] ?>" />
        <label>Name</label>
    </div>
    <div class="input-field">
        <textarea name="description" class="materialize-textarea"><?= $product['description']?></textarea>
        <label>Description</label>
    </div>
    <div class="input-field">
        <input name="arLink" type="text" class="validate" value="<?= $product['arLink'] ?>" />
        <label>Augmented Reality Link</label>
    </div>
    <div class="file-field input-field">
        <div class="btn indigo darken-4">
            <span>image</span>
            <input type="file" name="image" accept="image/*">
            <input type="hidden" name="imageBackend" value="<?= $result['imageFile'] ?>" />
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>
    <?php if ($updateMode) : ?>
        <div style="margin-bottom: 20px;">
            <h6>Display to Site</h6>
            <div class="switch">
                <label>
                    No
                    <input type="checkbox" name="enabled" <?= $updateMode ? ($product['enabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "checked" : "") : "" ?>>
                    <span class="lever"></span>
                    Yes
                </label>
            </div>
        </div>
        <button class="btn waves-effect waves-light blue" type="submit" name="action">Update<i class="material-icons left">edit</i></button>
    <?php else : ?>
        <button class="btn waves-effect waves-light" type="submit" name="action">Add<i class="material-icons left">add</i></button>
    <?php endif; ?>
</form>
<table class="striped">
    <thead>
        <tr>
            <th style="width: 20%">Name</th>
            <th style="width: 25%">Description</th>
            <th style="width: 15%">AR Link</th>
            <th style="width: 15%">Image</th>
            <th style="width: 10%">Status</th>
            <th style="width: 15%">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $product['name'] ?></td>
                <td><?= $product['description'] ?></td>
                <td>
                    <?php if (strlen(trim($product['arLink'])) == 0) : ?>
                        <strong>No Link Yet</strong>
                    <?php else : ?>
                        <a href="<?= $product['arLink'] ?>" target="_blank">Link</a>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if(strlen(trim($product['imageFile'])) == 0): ?>
                        <strong>No Link Yet</strong>
                    <?php else: ?>
                        <a href="<?= getenv('USE_LOCAL_FILESYSTEM') == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "/uploads/{$product['imageFile']}" : $product['imageFile']; ?>" target="_blank">Image</a>
                    <?php endif;?>
                </td>
                <td><?= $product['enabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Active" : "Disabled" ?></td>
                <td>
                    <a href="<?= "/cpanel/product/{$product['id']}" ?>"><i class="material-icons left">edit</i></a>
                    <a id="remove-<?= $product['id'] ?>" href="#" data-target="removeProduct" class="modal-trigger"><i class="material-icons left">delete</i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div id="removeProduct" class="modal">
    <div class="modal-content">
        <h4>Do you want to remove this Product ?</h4>
        <table>
            <tbody>
                <tr>
                    <th style="width: 25%">Name</th>
                    <td id="productName"></td>
                </tr>
            </tbody>
        </table>
        <input type="hidden" id="productId" />
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-light btn green lighten-1">No</a>
        <a href="#!" class="modal-close waves-effect waves-light btn red lighten-1" id="continueRemove">Yes</a>
    </div>
</div>
<script>
    $(document).ready(function() {
        <?php if (isset($notification)) : ?>
            M.toast({
                html: '<?= $notification ?>'
            });
        <?php endif; ?>

        $("#removeProduct").modal({
            onOpenStart: function(e, t) {
                let entries = t.id.split("-");
                let id = entries[1];
                $.ajax({
                    url: `/api/product/${id}`,
                    method: 'GET',
                }).done(function(data, status, xhr) {
                    console.log(data);
                    $("#productName").html(data.name);
                    $("#productId").val(data.id);
                }).fail(function(xhr, status, err) {
                    console.error(err);
                    throw err;
                });
            }
        });

        $('#continueRemove').click(function() {
            let id = $("#productId").val();
            $.ajax({
                url: `/api/product/${id}`,
                method: 'DELETE'
            }).done(function(data, status, xhr) {
                window.location = `/cpanel/town/<?= $townLink ?>/products`
            }).fail(function(xhr, status, err) {
                console.error(err);
                window.location = `/cpanel/town/<?= $townLink ?>/products`
            });
        });
    });
</script>