<div class="row">
    <div class="center">
        <!-- TODO add overview -->
        <h3 class="center">How do you want to retrieve our data?</h3>
    </div>
</div>

<div class="row">
    <div class="col s6 m6">
        <div class="center">
            <img class="responsive-img" src="/images/csv-icon.png" onclick="window.location='/open-data/csv'" style="cursor: pointer" />
            <h4>CSV</h4>
            <p>Our Open Data component has a CSV facility to support display of tabular data for sophisticated data analysis and processing.</p>
        </div>
    </div>
    <div class="col s6 m6">
        <div class="center">
            <img class="responsive-img" src="/images/rest-api-icon.png" onclick="window.location='/open-data/rest'" style="cursor: pointer" />
            <h4>REST</h4>
            <p>Want to use our data in your interactive charts and reports? Our Open Data component exposes a REST API specification for your needs.</p>
        </div>
    </div>
</div>