<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<link href="/assets/css/owl.carousel.min.css" rel="stylesheet"/>
<link href="/assets/css/owl.theme.default.min.css" rel="stylesheet"/>
<?php if(strlen(trim($imageSrc)) > 0): ?>
    <div class="parallax-container">
        <div class="parallax"><img src="<?= $imageSrc ?>" alt="Primary Image"></div>
    </div>
<?php endif;?>

<div class="section white">
    <div class="row container">
        <div class="col l12 m12 s12">
            <h3><?= $poi['name']; ?></h3>
            <div id="addDestination" class="chip green lighten-1 white-text"  style="cursor: pointer;"><img src="/images/add-bookmark.png"/>Add to my bookmarks</div>
            <div id="removeDestination" class="chip red lighten-1 white-text hide"  style="cursor: pointer;"><img src="/images/remove-bookmark.png"/>Remove from my bookmarks</div>
            <div class="chip blue lighten-1 white-text"  style="cursor: pointer;" onclick="window.location='https://www.google.com/maps/search/?api=1&query=<?= "{$poi['latitude']},{$poi['longitude']}"?>'"><img src="/images/google-map.png"/>View in Google Maps</div>
            <?php if (strcasecmp(ApplicationConstants::INDICATOR_NUMERIC_TRUE, $poi['arEnabled']) == 0  && strlen(trim($poi['arLink'])) > 0): ?>
                <div class="chip blue lighten-1 white-text" style="cursor: pointer;" onclick="window.location='<?= $poi['arLink'];?>'"><img src="/images/ar-enabled.png"/>View in AR</div>
            <?php endif;?>
        </div>
    </div>
    <div class="row container">
        <div class="col l6 m6 s12">
            <blockquote style="white-space: pre-line; text-align: justify;">
                <?= strlen($poi['description']) > 0 ? $poi['description'] : "To be formulated" ?>
            </blockquote>
            
            <?php if(count($poi['topicTags']) > 0): ?>
                <span style="font-weight: bold;">Tags:&nbsp;</span>
                <?php foreach($poi['topicTags'] as $tag): ?>
                    <div class="chip"><?= $tag['name']; ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <div class="show-on-small-only hide-on-med-and-up">
                <h6 style="margin-top: 10px;">Multimedia</h6>
                <?php include 'destination/_multimedia.phtml' ?>
            </div>
            <?php include 'destination/_detail.phtml' ?>
        </div>
        <div class="col l6 m6 show-on-med-and-up hide-on-small-only">
            <?php include 'destination/_multimedia.phtml' ?>
        </div>
    </div>
</div>
<script src="/assets/js/owl.carousel.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".collapsible").collapsible({
            accordion: false
        });

        $(".tooltipped").tooltip()

        $(".owl-carousel").owlCarousel({
            items: 1,
            autoHeight: true,
            lazyLoad:true,
            loop:true,
            margin:10
        });

        $('.parallax').parallax();

        let poi = {
            id: '<?= $id ?>', 
            name: '<?= $poi['name']?>',
            type: 'destination'
        }

        let bookmarks = localStorage.getItem('bookmarks');
        if (bookmarks != null && bookmarks.length > 0) {
            let bookmarkEntries = JSON.parse(bookmarks);
            for (let bookmark of bookmarkEntries) {
                if (poi.id == bookmark.id && bookmark.type == 'destination') {
                    $("#addDestination").addClass('hide');
                    $("#removeDestination").removeClass('hide');
                    break;
                }
            }
        }

        $("#addDestination").click(function() {
            if(!localStorage) {
                console.warn('Browser not supported');
                return;
            }

            $(this).addClass('hide');
            M.toast({
                html: '<?= $poi['name']?> is now bookmarked',
                displayLength: 1000,
                completeCallback: function() {
                    window.location = `/place/${poi.id}`
                }
            })
            $("#removeDestination").removeClass('hide');
            
            let bookmarks = localStorage.getItem('bookmarks');
            if (bookmarks == null || bookmarks.length == 0) {
                localStorage.setItem('bookmarks', JSON.stringify([poi]));
            } else {
                let bookmarkEntries = JSON.parse(bookmarks);
                bookmarkEntries.push(poi);
                localStorage.setItem('bookmarks', JSON.stringify(bookmarkEntries));
            }
        });

        $("#removeDestination").click(function() {
            $(this).addClass('hide');
            M.toast({
                html: '<?= $poi['name']?> removed from your bookmark',
                displayLength: 1000,
                completeCallback: function() {
                    window.location = `/place/${poi.id}`
                }
            })
            $("#addDestination").removeClass('hide');

            let bookmarks = localStorage.getItem('bookmarks');
            if (bookmarks != null && bookmarks.length > 0) {
                let bookmarkEntries = JSON.parse(bookmarks);
                let entries = [];
                for (let bookmark of bookmarkEntries) {
                    if (poi.id == bookmark.id && bookmark.type == 'destination') {
                        continue;
                    }
                    entries.push(bookmark);
                }
                localStorage.setItem('bookmarks', JSON.stringify(entries));
            }
        });

        $(".tooltip").tooltip();
    });
</script>