<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<html>

    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <title>Discover La Union</title>
    </head>

    <body>
        <div class="navbar-fixed">
            <nav class="blue darken-4">
                <div class="nav-wrapper blue darken-4 container">
                    <a href="#!" class="brand-logo">Discover La Union</a>
                    <a href="#" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="/">Home</a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <ul class="sidenav" id="mobile-menu">
            <li class="flow-text"><a href="/">Home</a></li>
        </ul>
        <div class="container">
            <div class="row" style="margin-top: 10px;">
                <div class="col s12 l12">
                    <div class="center">
                        <h5 class="flow-text">Discover the beauty of La Union, like you've never seen before.</h5>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12 l12">
                    <?php if (count($places) == 0) : ?>
                        <div class="center">
                            <img src="/images/no_records.png" class="responsive-img" />
                            <h6 class="center flow-text">Oops! It seems there are no places yet declared. Try again later or check out this <a href="/explore">site</a></h6>
                        </div>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($places as $place) : ?>
                                <li class="collection-item" style="cursor: pointer;" onclick="window.location='/place/<?= $place['id'] ?>'">
                                    <h5 class="flow-text"><?= $place['name'] ?></h5>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php include_once __DIR__."../../cpanel/footer.phtml";?>
    </body>
    
    <script>
        $(document).ready(function() {
            $('.sidenav').sidenav();
        });
    </script>

</html>