<!-- Northern Circuit Start -->
<div class="row">
    <h3>Northern Circuit</h3>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/balaoan.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/balaoan">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Balaoan<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/bangar.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/bangar">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Bangar<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/luna.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/luna">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Luna<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/santol.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/santol">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Santol<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/sudipen.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/sudipen">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Sudipen<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
</div>
<!-- Northern Circuit End -->

<!-- Central Circuit Start -->
<div class="row">
    <h3>Central Circuit</h3>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/bacnotan.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/bacnotan">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Bacnotan<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/san-fernando.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/san_fernando">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About San Fernando<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/san-gabriel.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/san_gabriel">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About San Gabriel<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/san-juan.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/san_juan">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About San Juan<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
</div>
<!-- Central Circuit End -->

<!-- Central Eastern Circuit Start -->
<div class="row">
    <h3>Central Eastern Circuit</h3>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/bauang.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/bauang">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Bauang<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/bagulin.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/bagulin">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Bagulin<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/burgos.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/burgos">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Burgos<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/naguilian.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/naguilian">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Naguilian<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
</div>
<!-- Central Eastern Circuit End -->

<!-- Southern Circuit Start -->
<div class="row">
    <h3>Southern Circuit</h3>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/agoo.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/agoo">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Agoo<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/aringay.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/aringay">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Aringay<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/caba.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/caba">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Caba<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/santo-tomas.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/santo_tomas">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Caba<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
</div>
<!-- Southern Circuit End -->

<!-- Southern Eastern Circuit Start -->
<div class="row">
    <h3>Southern Eastern Circuit</h3>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/pugo.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/pugo">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Pugo<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/rosario.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/rosario">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Rosario<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="images/tubao.jpg">
        </div>
        <div class="card-content">
            <p class="flow-text activator"><a href="/places/tubao">Explore</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4 flow-text">About Tubao<i class="material-icons right">close</i></span>
            <p class="flow-text">Description here</p>
        </div>
    </div>
</div>
<!-- Southern Eastern Circuit End -->

<script>
    $(document).ready(function() {
        $('.collapsible').collapsible();
    });
</script>