<div class="container">
    <div class="row">
        <div class="col s12 m12 l12" style="margin-top: 10px;">
            <h1 class="flow-text center-align teal-text text-darken-4" style="font-weight: bold;">Enjoy wonderful places in <span class="orange-text text-darken-4">La Union</span></h1>
            <ul class="collapsible popout">
                <li>
                    <div class="collapsible-header" style="background-color: rgb(0, 255, 1)">Northern Circuit</div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/balaoan'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/balaoan.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Pugo</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bangar'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/bangar.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Bangar</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 show-on-med-and-up hide-on-small-only">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/luna'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/luna.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Luna</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s6 show-on-small-only hide-on-med-and-up">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/luna'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/luna.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Luna</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col s6 show-on-small-only hide-on-med-and-up">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/santol'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/santol.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Santol</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 show-on-med-and-up hide-on-small-only">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/santol'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/santol.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Santol</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 show-on-med-and-up hide-on-small-only">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/sudipen'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/sudipen.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Sudipen</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                        <div class="row">
                            <div class="col s3 show-on-small-only hide-on-med-and-up">&nbsp;</div>
                            <div class="col s6 show-on-small-only hide-on-med-and-up">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/sudipen'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/sudipen.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Sudipen</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col s3 show-on-small-only hide-on-med-and-up">&nbsp;</div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header" style="background-color: rgb(255, 255, 1)">Central Circuit</div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bacnotan'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/bacnotan.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Bacnotan</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_fernando'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/san_fernando.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">San Fernando</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_gabriel'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/san_gabriel.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">San Gabriel</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_juan'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/san_juan.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">San Juan</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header" style="background-color: rgb(255, 127, 0)">Central Eastern Circuit</div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bauang'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/bauang.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Bauang</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bagulin'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/bagulin.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Bagulin</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/burgos'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/burgos.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Burgos</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/naguilian'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/naguilian.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Naguilian</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header" style="background-color: rgb(0, 128, 255)">Southern Circuit</div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/agoo'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/agoo.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Agoo</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/aringay'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/aringay.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Aringay</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                        <div class="row">
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/caba'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/caba.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Caba</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/santo_tomas'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/santo_tomas.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Santo Tomas</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header white-text" style="background-color: rgb(224, 0, 114);">South Eastern Circuit</div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/pugo'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/pugo.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Pugo</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 s6">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/rosario'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/rosario.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Rosario</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col l4 m4 show-on-med-and-up hide-on-small-only">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/tubao'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/tubao.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Tubao</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s3 show-on-small-only hide-on-med-and-up">&nbsp;</div>
                            <div class="col s6 show-on-small-only hide-on-med-and-up">
                                <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/tubao'">
                                    <div class="row valign-wrapper">
                                        <div class="col l3 m3 s3">
                                            <img src="/images/icons/tubao.png" class="black circle responsive-img" />
                                        </div>
                                        <div class="col l9 m9 s9">
                                            <h4 class="flow-text">Tubao</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col s3 show-on-small-only hide-on-med-and-up">&nbsp;</div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.collapsible').collapsible({
            accordion: false
        })
    });
</script>