<div class="container">
    <div class="row">
        <div class="col s12 m12 l12" style="margin-top: 10px;">
            <h3 class="center">Select a Tourism Circuit</h3>
            <ul class="tabs">
                <li class="tab col s2 m2 l2"><a href="#north">North</a></li>
                <li class="tab col s2 m2 l2"><a href="#central">Central</a></li>
                <li class="tab col s3 m3 l3"><a href="#central-east">Central Eastern</a></li>
                <li class="tab col s2 m2 l2"><a href="#south">South</a></li>
                <li class="tab col s3 m3 l3"><a href="#south-east">South Eastern</a></li>
            </ul>
            <div id="north" class="col s12 m12 l12">
                <div class="row" style="margin-top: 20px;">
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/balaoan'">Balaoan</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bangar'">Bangar</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/luna'">Luna</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/santol'">Santol</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/sudipen'">Sudipen</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
            </div>
            <div id="central" class="col s12 m12 l12">
                <div class="row" style="margin-top: 20px;">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bacnotan'">Bacnotan</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_fernando'">City of San Fernando</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
                <div class="row">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_gabriel'">San Gabriel</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/san_juan'">San Juan</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
            </div>
            <div id="central-east" class="col s12 m12 l12">
                <div class="row" style="margin-top: 20px;">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bauang'">Bauang</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/bagulin'">Bagulin</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
                <div class="row">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/burgos'">Burgos</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/naguilian'">Naguilian</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
            </div>
            <div id="south" class="col s12 m12 l12">
                <div class="row" style="margin-top: 20px;">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/agoo'">Agoo</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/aringay'">Aringay</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
                <div class="row">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/caba'">Caba</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/santo_tomas'">Santo Tomas</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
            </div>
            <div id="south-east" class="col s12 m12 l12">
                <div class="row" style="margin-top: 20px;">
                    <div class="col l2 m2 s2">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/pugo'">Pugo</div>
                    </div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/rosario'">Rosario</div>
                    </div>
                    <div class="col l2 m2 s2">&nbsp;</div>
                </div>
                <div class="row">
                    <div class="col l4 m4 s4">&nbsp;</div>
                    <div class="col l4 m4 s4">
                        <div class="card-panel" style="cursor: pointer" onclick="window.location='/places/tubao'">Tubao</div>
                    </div>
                    <div class="col l4 m4 s4">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var elem = document.querySelector('.collapsible.expandable');
    var instance = M.Collapsible.init(elem, {
        accordion: false
    });

    $(document).ready(function() {
        $('.tabs').tabs({
            swipeable: true
        })
    });
</script>