<div class="parallax-container">
    <div class="parallax">
        <img src="/images/home-banner.jpg">
    </div>
</div>

<div class="section white">
    <div class="row container">
        <h1 class="flow-text center-align teal-text text-darken-4" style="font-weight: bold;">Enjoy wonderful places in <span class="orange-text text-darken-4">La Union</span></h1>
        <div class="row">
            <div class="col l4 m4 s6">
                <div class="card-panel teal ligthen-1" style="cursor: pointer" onclick="window.location='/places/san_juan'">
                    <p class="white-text center-align flow-text">San Juan</p>
                </div>
            </div>
            <div class="col l4 m4 s6">
                <div class="card-panel red darken-2" style="cursor: pointer" onclick="window.location='/places/san_fernando'">
                    <p class="white-text center-align flow-text">City of San Fernando</p>
                </div>
            </div>
            <div class="col l4 m4 show-on-medium-and-up hide-on-small-only">
                <div class="card-panel orange darken-3" style="cursor: pointer" onclick="window.location='/places/bauang'">
                    <p class="white-text center-align flow-text">Bauang</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col s6 hide-on-med-and-up show-on-small">
                <div class="card-panel orange darken-3" style="cursor: pointer" onclick="window.location='/places/bauang'">
                    <p class="white-text center-align flow-text">Bauang</p>
                </div>
            </div>
            <div class="col s6 hide-on-med-and-up show-on-small">
                <div class="card-panel brown darken-2" style="cursor: pointer" onclick="window.location='/places/agoo'">
                    <p class="white-text center-align flow-text">Agoo</p>
                </div>
            </div>
            <div class="col l4 m4 show-on-medium-and-up hide-on-small-only">
                <div class="card-panel brown darken-2" style="cursor: pointer" onclick="window.location='/places/agoo'">
                    <p class="white-text center-align flow-text">Agoo</p>
                </div>
            </div>
            <div class="col l4 m4 show-on-medium-and-up hide-on-small-only">
                <div class="card-panel green darken-3" style="cursor: pointer" onclick="window.location='/places/pugo'">
                    <p class="white-text center-align flow-text">Pugo</p>
                </div>
            </div>
            <div class="col l4 m4 show-on-medium-and-up hide-on-small-only">
                <div class="card-panel indigo darken-4" style="cursor: pointer" onclick="window.location='/places/luna'">
                    <p class="white-text center-align flow-text">Luna</p>
                </div>
            </div>
        </div>

        <div class="row hide-on-med-and-up show-on-small">
            <div class="col s6 hide-on-med-and-up show-on-small">
                <div class="card-panel green darken-3" style="cursor: pointer" onclick="window.location='/places/pugo'">
                    <p class="white-text center-align flow-text">Pugo</p>
                </div>
            </div>
            <div class="col s6 hide-on-med-and-up show-on-small">
                <div class="card-panel indigo darken-4" style="cursor: pointer" onclick="window.location='/places/luna'">
                    <p class="white-text center-align flow-text">Luna</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.parallax').parallax();
    });
</script>