<div class="row">
    <div class="col l12 m12 sl12">
        <h1 class="flow-text center-align teal-text text-darken-4" style="font-weight: bold;">Enjoy wonderful places in <span class="orange-text text-darken-4">La Union</span></h1>
    </div>
</div>

<div class="row">
    <div class="col l4 m4 s4">
        <div class="card-panel teal ligthen-1" style="cursor: pointer" onclick="window.location='/places/san_juan'">
            <p class="white-text center-align">San Juan</p>
        </div>
    </div>
    <div class="col l4 m4 s4">
        <div class="card-panel red darken-2" style="cursor: pointer" onclick="window.location='/places/san_fernando'">
            <p class="white-text center-align">San Fernando</p>
        </div>
    </div>
    <div class="col l4 m4 s4">
        <div class="card-panel orange darken-3" style="cursor: pointer" onclick="window.location='/places/bauang'">
            <p class="white-text center-align">Bauang</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col l4 m4 s4">
        <div class="card-panel brown darken-2" style="cursor: pointer" onclick="window.location='/places/agoo'">
            <p class="white-text center-align">Agoo</p>
        </div>
    </div>
    <div class="col l4 m4 s4">
        <div class="card-panel green darken-3" style="cursor: pointer" onclick="window.location='/places/pugo'">
            <p class="white-text center-align">Pugo</p>
        </div>
    </div>
    <div class="col l4 m4 s4">
        <div class="card-panel indigo darken-4" style="cursor: pointer" onclick="window.location='/places/luna'">
            <p class="white-text center-align">Luna</p>
        </div>
    </div>
</div>