<!DOCTYPE html>
<html>

    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <style>
            i:hover {
                cursor: pointer
            }
        </style>
        <title>Welcome to La Union</title>
    </head>

    <body>
        <div class="container">
            <div class="row" style="margin-top: 50px;">
                <div class="col s12 l12">
                    <div class="center">
                        <h1>Welcome to La Union</h1>
                        <h5>Select an icon to proceed</h5>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col l4 s12">
                    <div class="center">
                        <i class="material-icons center large" onclick='window.location="/explore"'>explore</i>
                        <h6>Explore</h6>
                        <p>Discover the different tourist destinations that our province has to offer.</p>
                    </div>
                </div>
                <div class="col l4 hide-on-small-only">
                    <div class="center">
                        <i class="material-icons center large" onclick='window.location="/discover"'>search</i>
                        <h6>Discover</h6>
                        <p>Discover selected places using Augmented Reality and appreciate its beauty.</p>
                    </div>
                </div>
                <div class="col l4 hide-on-small-only">
                    <div class="center">
                        <i class="material-icons center large" onclick='window.location="/open-data"'>cloud_download</i>
                        <h6>Open Data</h6>
                        <p>Need Data? Our open data component gives you real-time raw data for analysis and consumption</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12 hide-on-large-only">
                    <div class="center">
                        <i class="material-icons center large" onclick='window.location="/discover"'>search</i>
                        <h6>Discover</h6>
                        <p>Discover select places using Augmented Reality</p>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>