<!DOCTYPE html>
<html lang="en">

    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <meta http-equiv="refresh" content="5;url=/home" />
        <title>Loading Page</title>
    </head>

    <body>
        <div class="container">
            <div class="row center" style="margin-top: 20px;">
                <img src="/images/elyuturismo-logo-600px.png" class="responsive-img" />
                <div class="progress">
                    <div class="determinate" id="progress-bar"></div>
                </div>
                <span class="flow-text" style="display: block;">Does not redirect? <a href="/home">Click here.</a></span>
            </div>
        </div>

        <script>
            let width = 20;
            setInterval(() => {
                if (width > 100) {
                    window.location = "/home"
                }
                document.getElementById('progress-bar').style.width = `${width}%`
                width += 20;
            }, 1000);
        </script>
    </body>

</html>