<!DOCTYPE html>
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
        <style>
            h6:hover {
                cursor: pointer
            }
        </style>
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom.css" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
        <title>ELYU TURISMO - <?= $title ?></title>
    </head>

    <body>
        <div class="navbar-fixed">
            <nav class="blue darken-4">
                <div class="nav-wrapper blue darken-4 container">
                    <a href="#!" class="brand-logo show-on-large hide-on-med-and-down"><?= $title ?></a>
                    <a href="#!" class="flow-text show-on-med-and-down hide-on-large-only"><?= $title ?></a>
                    <ul class="right">
                        <li>
                            <a href="#" data-target="mobile-menu" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <ul class="sidenav" id="mobile-menu">
            <li class="center">
                <img src="/images/elyuturismo-logo.png" class="responsive-img"/>
            </li>
            <li class="divider">&nbsp;</li>
            <li>
                <div class="row" style="margin-bottom: 0; padding-bottom: 0">
                    <div class="input-field col s12">
                        <label>Find a Tourist Destination</label>
                        <input type="text" class="autocomplete">
                    </div>
                </div>
            </li>
            <li class="divider">&nbsp;</li>
            <li>
                <a href="/destinations" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">explore</i>Destinations
                </a>
            </li>
            <li>
                <a href="/products" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">local_offer</i>Products
                </a>
            </li>
            <li>
                <a href="/bookmarks" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">bookmarks</i>My Bookmarks
                </a>
            </li>
            <li>
                <a href="/open-data" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">cloud_download</i>Open Data
                </a>
            </li>
        </ul>
        <div class="container">
            <?= $content ?>
        </div>
        <?php include_once __DIR__."../../cpanel/footer.phtml";?>
        <input type="hidden" id="destinationsBackend" value='<?= $destinationsBackend ?>'>
    </body>

    <script>
        $(document).ready(function() {
            $('.sidenav').sidenav();
            $('.collapsible').collapsible();

            let bookmarks = localStorage.getItem('bookmarks');
            $("#bookmarks").html(null);
            if (bookmarks == null || bookmarks.length == 0) {
                $("#bookmarks").append('<li><a style="display: block; padding-left: 30px;" class="flow-text" id="noBookmarks">No bookmarks yet.</a></li>');
            } else {
                let bookmarkEntries = JSON.parse(bookmarks);
                let entries = [];
                for (let bookmark of bookmarkEntries) {
                    entries.push(`<li><a href="/place/${bookmark.id}" style="display: block; padding-left: 30px; word-wrap: break-word;" class="flow-text waves-effect">${bookmark.name}</a></li>`);
                }

                if (entries.length > 0) {
                    $("#bookmarks").html(entries.join(""));
                } else {
                    $("#bookmarks").append('<li><a style="display: block; padding-left: 30px;" class="flow-text" id="noBookmarks">No bookmarks yet.</a></li>');
                }
            }

            $(".autocomplete").autocomplete({
                data: <?= $destinationAutocomplete; ?>,
                onAutocomplete: function(val) {
                    let destinations = JSON.parse($("#destinationsBackend").val());
                    for (let destination of destinations) {
                        if (val === destination.name) {
                            window.location = `/place/${destination.id}`
                            return;
                        }
                    }
                }
            })
        });
    </script>


</html>