<!DOCTYPE html>
<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
        <style>
            h6:hover {
                cursor: pointer
            }

            body {
                display: flex;
                min-height: 100vh;
                flex-direction: column;
            }

            main {
                flex: 1 0 auto;
            }
        </style>
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/custom.css" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <title>ELYU TURISMO - <?= $title ?></title>
    </head>

    <body>
        <div class="navbar-fixed">
            <nav class="teal darken-4">
                <div class="nav-wrapper teal darken-4 container">
                    <a href="/home" class="brand-logo show-on-large hide-on-med-and-down">
                        <img src="/images/elyuturismo-logo.png" style="width: 65px; height: 65px;" />
                    </a>
                    <a href="<?= isset($link) ? $link : "#!"?>" class="flow-text show-on-med-and-down hide-on-large-only"><?= $title ?></a>
                    <ul class="left show-on-med-and-down hide-on-large-only">
                        <li>
                            <a href="#" data-target="mobile-menu" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
                        </li>
                    </ul>
                    <ul class="right show-on-large hide-on-med-and-down">
                        <li>
                            <a href="/destinations">
                                <i class="material-icons left">explore</i>Destinations
                            </a>
                        </li>
                        <li>
                            <a href="/products">
                                <i class="material-icons left">local_offer</i>Products
                            </a>
                        </li>
                        <li>
                            <a href="/open-data">
                                <i class="material-icons left">cloud_download</i>Open Data
                            </a>
                        </li>
                        <li>
                            <a href="/bookmarks">
                                <i class="material-icons left">bookmarks</i>My Bookmarks
                            </a>
                        </li>
                        <li>
                            <a href="/search">
                                <i class="material-icons left">search</i>Search
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <ul class="sidenav" id="mobile-menu">
            <li class="center">
                <img src="/images/elyuturismo-logo.png" class="responsive-img" />
            </li>
            <li class="divider">&nbsp;</li>
            <li>
                <a href="/home" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons left">home</i>Home
                </a>
            </li>
            <li>
                <a href="/destinations" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">explore</i>Destinations
                </a>
            </li>
            <li>
                <a href="/products" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">local_offer</i>Products
                </a>
            </li>
            <li>
                <a href="/open-data" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">cloud_download</i>Open Data
                </a>
            </li>
            <li>
                <a href="/bookmarks" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">bookmarks</i>My Bookmarks
                </a>
            </li>
            <li>
                <a href="/search" style="display: block; font-weight: bold; padding: 0 17px">
                    <i class="material-icons">search</i>Search
                </a>
            </li>
        </ul>
        <main>
            <?= $content ?>
        </main>
        <?php include_once __DIR__ . "../../cpanel/footer.phtml"; ?>
    </body>

    <script>
        $(document).ready(function() {
            $('.sidenav').sidenav();
        });
    </script>
</html>