<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <title>What is <?= $poi['name'] ?></title>
</head>

<body>
    <div class="container">
        <div class="row" style="margin-top: 10px;">
            <div class="col s12 l12">
                <div class="center">
                    <h1><?= $poi['name'] ?></h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col l9 s12">
                <div class="center">
                    <img class="responsive-img" src="/uploads/<?= $poi['imageName'] ?>" />
                </div>
                <table>
                    <tbody>
                        <tr>
                            <th>Location</th>
                            <td>
                                <?= $poi['address']; ?>
                                <br />
                                <?= "Latitude: {$poi['latitude']}" ?>
                                <br />
                                <?= "Longitude: {$poi['longitude']}" ?>
                            </td>
                        </tr>
                        <tr>
                            <th>Classifications</th>
                            <td>
                                <?php foreach ($poi['classifications'] as $classification) : ?>
                                    <div class="chip blue lighten-2"><?= $classification['name'] ?></div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                        <tr>
                            <th>Tags</th>
                            <td>
                                <?php foreach ($poi['topicTags'] as $tag) : ?>
                                    <div class="chip red lighten-2"><?= $tag['name'] ?></div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div id="description"></div>

                <h6>Commuter's Guide</h6>
                <div id="commuterGuide"></div>

                <div class="hide-on-large-only">
                    <h6>Total Visits</h6>
                    <p><?= number_format($visitorCount[0]['visitorCount'], 2) ?></p>

                    <h6>Schedules</h6>
                    <?php if (count($schedules) == 0) : ?>
                        <p>No Schedules Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($schedules as $schedule) : ?>
                                <li class="collection-item">
                                    <h6><?= $schedule['openEveryday'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Everyday" : (is_null($schedule['day']) ? $schedule['specificDate'] : $schedule['day']) ?></h6>
                                    <p><?= $schedule['openAllDay'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "24 hours" : $schedule['operatingHours'] ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <h6 style="margin-top: 50px">Fees</h6>
                    <?php if (count($fees) == 0) : ?>
                        <p>No Fees Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($fees as $fee) : ?>
                                <li class="collection-item">
                                    <h6><?= $fee['description'] ?></h6>
                                    <p><?= $fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Free Admission" : "PHP " . number_format($fee['amount'], 2) ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col l3 hide-on-med-and-down">
                <h6>Total Visits</h6>
                <p><?= number_format($visitorCount[0]['visitorcount']) ?> visitors</p>

                <h6 style="margin-top: 20px;">Schedules</h6>
                <?php if (count($schedules) == 0) : ?>
                    <p>No Schedules Yet</p>
                <?php else : ?>
                    <ul class="collection">
                        <?php foreach ($schedules as $schedule) : ?>
                            <li class="collection-item">
                                <h6><?= $schedule['openEveryday'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Everyday" : (is_null($schedule['day']) ? $schedule['specificDate'] : $schedule['day']) ?></h6>
                                <p><?= $schedule['openAllDay'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "24 hours" : $schedule['operatingHours'] ?></p>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>

                <h6 style="margin-top: 20px">Fees</h6>
                <?php if (count($fees) == 0) : ?>
                    <p>No Fees Yet</p>
                <?php else : ?>
                    <ul class="collection">
                        <?php foreach ($fees as $fee) : ?>
                            <li class="collection-item">
                                <h6><?= $fee['description'] ?></h6>
                                <p><?= $fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Free Admission" : "PHP " . number_format($fee['amount'], 2) ?></p>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</body>

<script type="text/javascript">
    $(document).ready(function() {
        let descriptionView = new Quill('#description', {
            theme: 'bubble'
        })
        descriptionView.disable();
        descriptionView.setContents(<?= $poi['descriptionwysiwyg']; ?>);

        let commuterGuideView = new Quill('#commuterGuide', {
            theme: 'bubble'
        })
        commuterGuideView.disable();
        commuterGuideView.setContents(<?= $poi['commuterguidewysiwyg']; ?>);
    });
</script>

</html>