<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<html>

    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
        <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
        <style type="text/css">
            .ql-editor strong {
                font-weight: bold;
            }

            .ql-container {
                height: 200px;
                overflow-y: auto;
            }
        </style>
        <title>What is <?= $poi['name'] ?></title>
    </head>

    <body>
        <div class="navbar-fixed">
            <nav class="blue darken-4">
                <div class="nav-wrapper blue darken-4 container">
                    <a href="/places/<?= strtolower(implode('_', explode(' ', $poi['town']))) ?>" class="brand-logo">Explore <?= $poi['town'] ?></a>
                    <a href="#" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="/">Home</a></li>
                        <li><a href="/explore">Explore</a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <ul class="sidenav" id="mobile-menu">
            <li><a href="/explore">Explore</a></li>
            <li><a href="/">Home</a></li>
        </ul>
        <div class="container">
            <div class="row valign-wrapper" style="margin-top: 10px;">
                <div class="col l6 hide-on-med-and-down">
                    <img class="responsive-img" src="/uploads/<?= $poi['imageName'] ?>" />
                </div>
                <div class="col l6 hide-on-med-and-down">
                    <h3>
                        <?= $poi['name'] ?>
                        <?php if($poi['arEnabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE): ?>
                            <span class="new badge blue black-text" data-badge-caption="AR Available">&nbsp;</span>
                        <?php endif;?>
                    </h3>
                    <table>
                        <tbody>
                            <?php if($poi['arEnabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE): ?>
                                <tr>
                                    <td colspan="2"><a href="<?= $arLink?>" target="_blank">Augmented Reality</a></td>
                                </tr>
                            <?php endif;?>
                            <tr>
                                <th>Location</th>
                                <td>
                                    <?= $poi['address']; ?>
                                    <br />
                                    <a target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= "{$poi['latitude']},{$poi['longitude']}" ?>">View on Google Maps</a>
                                </td>
                            </tr>
                            <tr>
                                <th>Classifications</th>
                                <td>
                                    <?php foreach ($poi['classifications'] as $classification) : ?>
                                        <div class="chip blue lighten-2"><?= $classification['name'] ?></div>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                            <tr>
                                <th>Tags</th>
                                <td>
                                    <?php foreach ($poi['topicTags'] as $tag) : ?>
                                        <div class="chip red lighten-2"><?= $tag['name'] ?></div>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col l9 hide-on-med-and-down">
                    <?php if (strlen($poi['description']) == 0) : ?>
                        <p style="font-style: italic">To be formulated</p>
                    <?php else : ?>
                        <div id="description"></div>
                    <?php endif; ?>

                    <h6>Commuter's Guide</h6>
                    <?php if (strlen($poi['commuterguide']) == 0) : ?>
                        <p style="font-style: italic">To be formulated</p>
                    <?php else : ?>
                        <div id="commuterGuide"></div>
                    <?php endif; ?>
                </div>
                <div class="col l3 hide-on-med-and-down">
                    <h6>Total Visits</h6>
                    <p><?= number_format($visitorCount[0]['visitorcount']) ?> visitors</p>

                    <h6 style="margin-top: 20px;">Schedules</h6>
                    <?php if (count($schedules) == 0) : ?>
                        <p>No Schedules Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($schedules as $schedule) : ?>
                                <li class="collection-item">
                                    <h6><?= $schedule['openEveryday'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Everyday" : (is_null($schedule['day']) ? $schedule['specificDate'] : $schedule['day']) ?></h6>
                                    <p><?= $schedule['openAllDay'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "24 hours" : $schedule['operatingHours'] ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <h6 style="margin-top: 20px">Fees</h6>
                    <?php if (count($fees) == 0) : ?>
                        <p>No Fees Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($fees as $fee) : ?>
                                <li class="collection-item">
                                    <h6><?= $fee['description'] ?></h6>
                                    <p><?= $fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Free Admission" : "PHP " . number_format($fee['amount'], 2) ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">
                <div class="col s12 hide-on-large-only">
                    <div class="center">
                        <img class="responsive-img" src="/uploads/<?= $poi['imageName'] ?>" />
                        <h3><?= $poi['name'] ?></h3>
                        <?php if($poi['arEnabled'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE): ?>
                            <a href="<?= $arLink?>" target="_blank">Augmented Reality</a>
                        <?php endif;?>
                    </div>
                    <table>
                        <tbody>
                            <tr>
                                <th>Location</th>
                                <td>
                                    <?= $poi['address']; ?>
                                    <br />
                                    <a target="_blank" href="https://www.google.com/maps/search/?api=1&query=<?= "{$poi['latitude']},{$poi['longitude']}" ?>">View on Google Maps</a>
                                </td>
                            </tr>
                            <tr>
                                <th>Classifications</th>
                                <td>
                                    <?php foreach ($poi['classifications'] as $classification) : ?>
                                        <div class="chip blue lighten-2"><?= $classification['name'] ?></div>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                            <tr>
                                <th>Tags</th>
                                <td>
                                    <?php foreach ($poi['topicTags'] as $tag) : ?>
                                        <div class="chip red lighten-2"><?= $tag['name'] ?></div>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php if (strlen($poi['description']) == 0) : ?>
                        <p style="font-style: italic">To be formulated</p>
                    <?php else : ?>
                        <div id="description-mobile"><?= $poi['description'] ?></div>
                    <?php endif; ?>

                    <h6>Commuter's Guide</h6>
                    <?php if (strlen($poi['commuterguide']) == 0) : ?>
                        <p style="font-style: italic">To be formulated</p>
                    <?php else : ?>
                        <div id="commuterGuide-mobile"></div>
                    <?php endif; ?>

                    <h6 style="margin-top: 20px;">Schedules</h6>
                    <?php if (count($schedules) == 0) : ?>
                        <p>No Schedules Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($schedules as $schedule) : ?>
                                <li class="collection-item">
                                    <h6><?= $schedule['openEveryday'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Everyday" : (is_null($schedule['day']) ? $schedule['specificDate'] : $schedule['day']) ?></h6>
                                    <p><?= $schedule['openAllDay'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "24 hours" : $schedule['operatingHours'] ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <h6 style="margin-top: 20px">Fees</h6>
                    <?php if (count($fees) == 0) : ?>
                        <p>No Fees Yet</p>
                    <?php else : ?>
                        <ul class="collection">
                            <?php foreach ($fees as $fee) : ?>
                                <li class="collection-item">
                                    <h6><?= $fee['description'] ?></h6>
                                    <p><?= $fee['freePrice'] == ApplicationConstants::INDICATOR_NUMERIC_TRUE ? "Free Admission" : "PHP " . number_format($fee['amount'], 2) ?></p>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <h6>Total Visits</h6>
                    <p><?= number_format($visitorCount[0]['visitorcount']) ?> visitors</p>
                </div>
            </div>
        </div>
    </body>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.sidenav').sidenav();

            let descriptionView = new Quill('#description', {
                theme: 'bubble'
            })
            descriptionView.disable();
            descriptionView.setContents(<?= $poi['descriptionwysiwyg']; ?>);

            let descriptionMobileView = new Quill('#description-mobile', {
                theme: 'bubble'
            })
            descriptionMobileView.disable();
            descriptionMobileView.setContents(<?= $poi['descriptionwysiwyg']; ?>);

            let commuterGuideView = new Quill('#commuterGuide', {
                theme: 'bubble'
            })
            commuterGuideView.disable();
            commuterGuideView.setContents(<?= $poi['commuterguidewysiwyg']; ?>);

            let commuterGuideMobileView = new Quill('#commuterGuide-mobile', {
                theme: 'bubble'
            })
            commuterGuideMobileView.disable();
            commuterGuideMobileView.setContents(<?= $poi['commuterguidewysiwyg']; ?>);
        });
    </script>

</html>