<!-- <?php

        use gov\pglu\tourism\util\ApplicationConstants;
        ?>
<div class="row" style="margin-top: 10px;">
    <div class="col s12 l12">
        <div class="center">
            <img src="/images/<?= strtolower(implode('-', explode(' ', $town))) ?>.jpg" class="responsive-img" alt="banner"/>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12 m12 l12">
        <h3 class="flow-text">Tourist Destinations</h3>
        <?php if (count($places) == 0) : ?>
            <div class="card-panel red lighten-2">
                <strong class="flow-text white-text">No Available Data</strong>
            </div>
        <?php else : ?>
            <?php foreach ($places as $place) : ?>
                <div class="card small">
                    <div class="card-image">
                        <img src="<?= $place['imageName'] ?>" class="responsive-img materialboxed" alt="No Image"/>
                    </div>
                    <div class="card-content">
                        <p class="flow-text"><?= $place['name']; ?></p>
                    </div>
                    <div class="card-action">
                        <a href="/place/<?= $place['id'] ?>">View</a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <div class="col s12 m12 l12">
        <h3 class="flow-text">Points of Interest</h3>
        <a href="https://www.google.com/maps/search/?api=1&query=<?= implode('+', explode(' ', $town)) . ",+La+Union" ?>" class="flow-text" style="display: block" target="_blank">View in Google Maps</a>
    </div>
</div>
<div class="row">
    <div class="col s12 m12 l12">
        <h3 class="flow-text">Products</h3>
        <?php if (count($townProducts) == 0) : ?>
            <div class="card-panel red lighten-2">
                <strong class="flow-text white-text">No Available Data</strong>
            </div>
        <?php else : ?>
            <?php foreach ($townProducts as $product) : ?>
                <div class="card small">
                    <div class="card-image">
                        <img src="<?= $product['imageFile'] ?>" class="responsive-img materialboxed" alt="No Image"/>
                    </div>
                    <div class="card-content">
                        <p class="flow-text"><?= $product['name']; ?></p>
                    </div>
                    <div class="card-action">
                        <a href="/product/<?= $product['id'] ?>">View</a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<div class="row">
    <div class="col s12 m12 l12">
        <h3 class="flow-text">Open Data</h3>
        <?php if (count($places) == 0) : ?>
            <div class="card-panel red lighten-2">
                <strong class="flow-text white-text">No Available Data</strong>
            </div>
        <?php else : ?>
            <canvas id="visitorCountChart" width="400" height="200"></canvas>
        <?php endif; ?>
    </div>
</div>
<script>
    var ctx = document.getElementById('visitorCountChart');
    var myChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: <?= $openData['places'] ?>,
            datasets: [{
                label: 'Number of Visitors',
                data: <?= $openData['values'] ?>
            }]
        },
        options: {
            scales: {
                xAxes: [{
                    ticks: {
                        beginAtZero: true,
                        stepSize: <?= floor($openData['maxCount'] * 0.25) ?>,
                        suggestedMin: 0,
                        suggestedMax: <?= $openData['maxCount'] + 100 ?>
                    }
                }]
            }
        }
    });

    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.materialboxed');
        var instances = M.Materialbox.init(elems);
    });
</script> -->

<div class="parallax-container">
    <div class="parallax"><img src="<?= $bannerImage ?>" alt="Banner Image"></div>
</div>

<div class="section white">
    <div class="row container">
        <div class="col l12 m12 s12">
            <h2 class="header">About <?= $town['name'] ?></h2>
            <p class="flow-text" style="white-space: pre-line">
                <?= strlen(trim($town['description'])) ? $town['description'] : "<i>To be defined.</i>" ?>
            </p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.parallax').parallax();
    });
</script>