<div class="container">
    <div class="row">
        <div class="col l12 m12 s12">
            <h1 class="center">Privacy and Usage Policy</h1>
            <blockquote>We are committed to protect the privacy of our website visitors and we will only collect, record, store, process, and use your personal information in accordance with Republic Act No. 10173 or the Data Privacy Act of 2012 and other pertinent laws. The outline below provides for the manner by which we manage the personal information that we will obtain from you if you visit our website.</blockquote>
        
            <h5>Collection of Personal Information</h5>
            <ul class="browser-default">
                <li>In downloading the open data records of this website, you will be asked for your e-mail address.</li>
                <li>In filing for intellectual property or copyright claims, you will be asked with the following: name and e-mail address or mobile number.</li>
            </ul>

            <h5>Purpose of Collecting Personal Information</h5>
            <ul class="browser-default">
                <li>The e-mail address prompted in open data records is only to be used for tracking purposes. The tracking mechanism will be used for future analysis on the frequency of downloads per record type and the user (e-mail address).</li>
                <li>The name and e-mail address or mobile number that are prompted on filing intellectual property or copyright claims is to provide the developer or webmaster an identification of complainant and contact the complainant for follow-up investigation or verification.</li>
            </ul>

            <h5>Disclosure and Retention of Personal Information</h5>
            <ul class="browser-default">
                <li>The scope of your personal information is only to this website and will not be shared to third-party entities.</li>
            </ul>

            <h5>Contact Us</h5>
            <ul class="browser-default">
                <li>For other concerns or question, please contact the developer at this <a href="mailto:ajocampo@lorma.edu">email</a> or to the <a href="#">webmaster</a></li>
            </ul>
        </div>
    </div>
</div>