<?php

use gov\pglu\tourism\util\ApplicationConstants;
?>
<link href="/assets/css/owl.carousel.min.css" rel="stylesheet"/>
<link href="/assets/css/owl.theme.default.min.css" rel="stylesheet"/>
<?php if(strlen(trim($imageSrc)) > 0): ?>
    <div class="parallax-container">
        <div class="parallax"><img src="<?= $imageSrc ?>" alt="Primary Image"></div>
    </div>
<?php endif;?>

<div class="section white">
    <div class="row container">
        <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
        <div class="col l8 m8 s12">
            <h3><?= $product['name']; ?></h3>
            <div class="chip white-text teal darken-4">
                <img src="/images/location.png"/>
                <?= "Town: {$product['town']}"  ?>
            </div>
            <div id="addDestination" class="chip green lighten-1 white-text"  style="cursor: pointer;"><img src="/images/add-bookmark.png"/>Add to my bookmarks</div>
            <div id="removeDestination" class="chip red lighten-1 white-text hide"  style="cursor: pointer;"><img src="/images/remove-bookmark.png"/>Remove from my bookmarks</div>
            <?php if (strlen(trim($product['arLink'])) > 0): ?>
                <div class="chip blue lighten-1 white-text" style="cursor: pointer;" onclick="window.location='<?= $product['arLink'];?>'"><img src="/images/ar-enabled.png"/>View in AR</div>
            <?php endif;?>

            <blockquote style="white-space: pre-line; text-align: justify;">
                <?= strlen($product['description']) > 0 ? $product['description'] : "To be formulated" ?>
            </blockquote>

            <?php if($imageCount > 0): ?>
                <div class="owl-carousel owl-theme">
                    <?php if(strlen($imageSrc) > 0): ?>
                        <img data-src="<?= $imageSrc ?>" alt="" class="owl-lazy responsive">
                    <?php endif; ?>
                    <?php foreach($images as $image): ?>
                        <img data-src="<?= $image ?>" alt="" class="owl-lazy responsive">
                    <?php endforeach; ?>
                </div>
                <?php if(strlen(trim($product['photoCredit']))): ?>
                    <span style="font-weight: bold">
                        Images by:&nbsp;
                    </span>
                    <ul class="browser-default">
                        <?php foreach(explode(',', $product['photoCredit']) as $photoCredit): ?>
                            <li><?= $photoCredit; ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
    </div>
</div>

<script src="/assets/js/owl.carousel.min.js"></script>
<script>
    $(document).ready(function() {
        $('.parallax').parallax();

        $(".owl-carousel").owlCarousel({
            items: 1,
            autoHeight: true,
            lazyLoad:true,
            loop:true,
            margin:10
        });

        let product = {
            id: '<?= $product['id']?>',
            name: '<?= $product['name']?>',
            type: 'product'
        }

        let bookmarks = localStorage.getItem('bookmarks');
        if (bookmarks != null && bookmarks.length > 0) {
            let bookmarkEntries = JSON.parse(bookmarks);
            for (let bookmark of bookmarkEntries) {
                if (product.id == bookmark.id && bookmark.type == 'product') {
                    $("#addProduct").addClass('hide');
                    $("#removeProduct").removeClass('hide');
                    break;
                }
            }
        }

        $("#addProduct").click(function() {
            $(this).addClass('hide');
            M.toast({
                html: `${product.name} is now bookmarked`,
                displayLength: 1000,
                completeCallback: function() {
                    window.location = `/product/${product.id}`
                }
            })
            $("#removeProduct").removeClass('hide');
            
            let bookmarks = localStorage.getItem('bookmarks');
            if (bookmarks == null || bookmarks.length == 0) {
                localStorage.setItem('bookmarks', JSON.stringify([product]));
            } else {
                let bookmarkEntries = JSON.parse(bookmarks);
                bookmarkEntries.push(product);
                localStorage.setItem('bookmarks', JSON.stringify(bookmarkEntries));
            }
        });

        $("#removeProduct").click(function() {
            $(this).addClass('hide');
            M.toast({
                html: `${product.name} removed from your bookmark`,
                displayLength: 1000,
                completeCallback: function() {
                    window.location = `/product/${product.id}`
                }
            })
            $("#addProduct").removeClass('hide');

            let bookmarks = localStorage.getItem('bookmarks');
            if (bookmarks != null && bookmarks.length > 0) {
                let bookmarkEntries = JSON.parse(bookmarks);
                let entries = [];
                for (let bookmark of bookmarkEntries) {
                    if (product.id == bookmark.id && bookmark.type == 'product') {
                        continue;
                    }
                    entries.push(bookmark);
                }
                localStorage.setItem('bookmarks', JSON.stringify(entries));
            }
        })

        $(".tooltip").tooltip();
    })
</script>