<div class="container">
    <div class="row">
        <div class="col l12 m12 s12">
            <h1 class="flow-text center-align teal-text text-darken-4" style="font-weight: bold;">Can't find a destination or product? Find it here...</span></h1>
        </div>
    </div>
    <div class="row">
        <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
        <div class="col l8 m8 s12">
            <div class="input-field">
                <i class="material-icons prefix">search</i>
                <input type="text" class="autocomplete" placeholder="Find a destination or product"/>
            </div>
        </div>
        <div class="col l2 m2 show-on-med-and-up hide-on-small-only">&nbsp;</div>
    </div>
    <input type="hidden" id="backend" value='<?= $backend ?>'>
</div>
<script>
    $(document).ready(function() {
        $(".autocomplete").autocomplete({
            data: <?= $entries ?>,
            onAutocomplete: function(v) {
                let entries = JSON.parse($("#backend").val());
                for(let entry of entries) {
                    if (v === entry.name) {
                        window.location = entry.link;
                    }
                }
            }
        })
    })
</script>