<div class="col l2">
    &nbsp;
</div>

<div class="col l8">
    <div class="section">
        <h3><i class="material-icons">add_location</i>&nbsp;Declare a Tourist Location</h3>
    </div>
    <div class="row">
        <form action="/poi/add" method="post" class="col l12">
            <div class="input-field">
                <input name="name" type="text" class="validate"/>
                <label>Name</label>
            </div>
            <div class="input-field">
                <input name="address" type="text" class="validate"/>
                <label>Address</label>
            </div>
            <div class="row">
                <div class="input-field col l6">
                    <input name="latitude" type="text" class="validate"/>
                    <label>Latitude</label>
                </div>
                <div class="input-field col l6">
                    <input name="longitude" type="text" class="validate"/>
                    <label>Longitude</label>
                </div>
            </div>
            <div class="row">
                
            </div>
        </form>
    </div>
</div>

<div class="col l2">
    &nbsp;
</div>