<div class="col l2">
    &nbsp;
</div>

<div class="col l8">
    <div class="section">
        <h3>Declare a Tourist Location</h3>
    </div>
    <div class="row">
        <form method="post" class="col l12" name="poiForm">
            <div class="input-field">
                <input name="name" type="text" class="validate" required/>
                <label>Name</label>
            </div>
            <div class="row">
                <div class="input-field col l8">
                    <textarea name="address" class="materialize-textarea validate" required></textarea>
                    <label>Address</label>
                </div>
                <div class="input-field col l4">
                    <select name="town" class="validate" required>
                        <option value="" disabled selected>Select town</option>
                        <?php foreach($circuits as $circuit => $towns): ?>
                            <optgroup label="<?=$circuit?>">
                                <?php foreach($towns as $town): ?>
                                    <option value="<?=$town?>"><?=$town?></option>
                                <?php endforeach;?>
                            </optgroup>
                        <?php endforeach;?>
                    </select>
                    <label>Tourism Ciruit and Town</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col l6">
                    <input name="latitude" type="text" class="validate" required/>
                    <label>Latitude</label>
                </div>
                <div class="input-field col l6">
                    <input name="longitude" type="text" class="validate" required/>
                    <label>Longitude</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col l6">
                    <p>Classifications</p>
                    <div id="tourist-classification"></div>
                    <input type="hidden" name="classifications"/>
                    <input type="hidden" id="classificationsBackend" value='<?=$classificationsBackend?>'/>
                </div>
                <div class="input-field col l6">
                    <p>Topic Tags</p>
                    <div id="tourist-tags"></div>
                    <input type="hidden" name="topicTags"/>
                    <input type="hidden" id="tagsBackend" value='<?=$tagsBackend?>'/>
                </div>
            </div>
            <button class="btn waves-effect waves-light" type="submit" name="action">Add<i class="material-icons left">add_location</i></button>
        </form>
    </div>
</div>

<div class="col l2">
    &nbsp;
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('select').formSelect();

        $("[name=poiForm]").submit(function() {
            event.preventDefault();
            $.ajax({
                url: '/api/poi/add',
                method: 'POST',
                data: {
                    name: $("[name=name]").val(),
                    address: $("[name=address]").val(),
                    town: $("[name=town]").val(),
                    latitude: $("[name=latitude]").val(),
                    longitude: $("[name=longitude]").val(),
                    classifications: $("[name=classifications]").val(),
                    topicTags: $("[name=topicTags]").val()
                }
            }).done(function(data, status, xhr) {
                console.log(data);
                M.toast({ 
                    html: data.message,
                    displayLength: 500,
                    completeCallback: function() {
                        window.location = `/poi/${data.id}`
                    }
                });
            }).fail(function(xhr, status, err) {
                console.error(err);
                M.toast({ 
                    html: 'Something went wrong. Try again later',
                    displayLength: 2000,
                    completeCallback: function() {
                        window.location = "/poi"
                    }
                })
            });
        });

        $("#tourist-classification").chips({
            placeholder: 'Classification',
            secondaryPlaceholder: 'Classification',
            autocompleteOptions: {
                data: <?=$classifications?>
            },
            onChipAdd: function(e, chip) {
                let rawData = $("#classificationsBackend").val();
                let data = JSON.parse(rawData);
                let classifications = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    classifications.push(result[0]);
                }
                $("[name=classifications]").val(JSON.stringify(classifications));
            },
            onChipDelete: function(e, chip) {
                let rawData = $("#classificationsBackend").val();
                let data = JSON.parse(rawData);
                let classifications = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    classifications.push(result[0]);
                }
                $("[name=classifications]").val(JSON.stringify(classifications));
            }
        })

        $("#tourist-tags").chips({
            placeholder: 'Topic Tags',
            secondaryPlaceholder: 'Topic Tags',
            autocompleteOptions: {
                data: <?=$tags?>
            },
            onChipAdd: function(e, chip) {
                let rawData = $("#tagsBackend").val();
                let data = JSON.parse(rawData);
                let tags = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    tags.push(result[0]);
                }
                $("[name=topicTags]").val(JSON.stringify(tags));
            },
            onChipDelete: function(e, chip) {
                let rawData = $("#tagsBackend").val();
                let data = JSON.parse(rawData);
                let tags = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    tags.push(result[0]);
                }
                $("[name=topicTags]").val(JSON.stringify(tags));
            }
        })
    });
</script>