<h2>Points of Interest</h2>
<a class="waves-light btn-large" href="/poi/add"><i class="material-icons left">create</i>Create</a>
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Location</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>