<h2>Manage Tags</h2>
<form method="post" action="/tag/add">
    <div class="input-field col l10">
        <input id="tag" type="text" class="validate" name="tag" required>
        <label for="tag">Tag Title</label>
    </div>
    <div class="input-field col l2">
        <button class="btn waves-effect waves-light" type="submit" name="action">add
            <i class="material-icons right">add</i>
        </button>
    </div>
</form>
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($tags as $tag): ?>
        <tr>
            <td><?php echo $tag['name']; ?></td>
            <td>&nbsp;</td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>