<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <title>PGLU Tourism Control Panel</title>
    </head>

    <body>
        <div class="navbar-fixed">
            <nav class="indigo darken-4">
                <div class="nav-wrapper container">
                    <a href="/" class="brand-logo">PGLU Tourism Control Panel</a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="/poi">Places Of Interest</a></li>
                        <li><a href="/discovery">Discoveries</a></li>
                        <li>
                            <a class="dropdown-trigger" href="#!" data-target="settingsDropdown">Settings<i class="material-icons right">arrow_drop_down</i></a>
                            <ul id="settingsDropdown" class="dropdown-content">
                                <li><a href="/tags">Tags</a></li>
                                <li class="divider">&nbsp;</li>
                                <li><a href="/classifications">Tourist Area Classification</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="container">
            <div class="row">
                <?= $content ?>
            </div>
        </div>

        <footer class="page-footer grey">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text">Footer Content</h5>
                        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                    </div>
                    <div class="col l4 offset-l2 s12">
                        <h5 class="white-text">Links</h5>
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    &copy; <?php echo date('Y')?> Copyright
                    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
                </div>
            </div>
        </footer>

        <script type="text/javascript">
            $(document).ready(function() {
                $(".dropdown-trigger").dropdown({
                    hover: false
                });   
            });
        </script>
    </body>
</html>