<table>
    <tbody>
        <tr>
            <th style="width: 25%;">Name</th>
            <td><?= $name ?></td>
        </tr>
    </tbody>
</table>
<div class="row">
    <div class="col l6">
        <h6 class="tooltip" data-position="top" data-tooltip="Activating this feature marks the POI to open an AR (artificial reality) application for immersive interaction.">Enable AR</h6>
        <div class="switch">
            <label>
                No
                <input type="checkbox" name="arEnabled" <?= $arEnabled == 1 ? "checked" : "" ?>>
                <span class="lever"></span>
                Yes
            </label>
        </div>
    </div>

    <div class="col l6">
        <h6 class="tooltip" data-position="top" data-tooltip="Activating this feature will display the place of interest in the website.">Display to Website</h6>
        <div class="switch">
            <label>
                No
                <input type="checkbox" name="displayable" <?= $displayable == 1 ? "checked" : ""; ?>>
                <span class="lever"></span>
                Yes
            </label>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('.tooltip').tooltip();

        $("[name=displayable]").change(function() {
            let indicator = $(this).is(":checked") ? 1 : 0;
            $.ajax({
                url: `/api/poi/<?= $id ?>/toggle/display/${indicator}`,
                method: 'PATCH'
            }).done(function(data, status, xhr) {
                M.toast({
                    html: data.message
                });
            }).fail(function(xhr, status, err) {
                console.error(err);
                M.toast({
                    html: 'Something went wrong. Try again later'
                })
            });
        });

        $("[name=arEnabled]").change(function() {
            let indicator = $(this).is(":checked") ? 1 : 0;
            $.ajax({
                url: `/api/poi/<?= $id ?>/toggle/ar/${indicator}`,
                method: 'PATCH'
            }).done(function(data, status, xhr) {
                M.toast({
                    html: data.message
                });
            }).fail(function(xhr, status, err) {
                console.error(err);
                M.toast({
                    html: 'Something went wrong. Try again later'
                })
            });
        });
    })
</script>