<div class="section">
    <h5>Update Basic Information</h5>
</div>
<form name="poiForm" enctype="multipart/form-data" action="<?="/cpanel/poi/{$id}/edit"?>" method="post">
    <div class="input-field">
        <input name="name" type="text" class="validate" required value="<?= $result['name'] ?>" />
        <label>Name</label>
    </div>
    <div class="row">
        <div class="input-field col l8">
            <textarea name="address" class="materialize-textarea validate" required><?= $result['address'] ?></textarea>
            <label>Address</label>
        </div>
        <div class="input-field col l4">
            <select name="town" class="validate" required>
                <option value="" disabled selected>Select town</option>
                <?php foreach ($circuits as $circuit => $towns) : ?>
                    <optgroup label="<?= $circuit ?>">
                        <?php foreach ($towns as $town) : ?>
                            <?php if (strcasecmp($result['town'], $town) == 0) : ?>
                                <option value="<?= $town ?>" selected><?= $town ?></option>
                            <?php else : ?>
                                <option value="<?= $town ?>"><?= $town ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </optgroup>
                <?php endforeach; ?>
            </select>
            <label>Tourism Ciruit and Town</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l6">
            <input name="latitude" type="text" class="validate" required value="<?= $result['latitude'] ?>" />
            <label>Latitude</label>
        </div>
        <div class="input-field col l6">
            <input name="longitude" type="text" class="validate" required value="<?= $result['longitude'] ?>" />
            <label>Longitude</label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col l6">
            <p>Classifications</p>
            <div id="tourist-classification"></div>
            <input type="hidden" name="classifications" value='<?= $assignedClassificationsBackend ?>' />
            <input type="hidden" id="classificationsBackend" value='<?= $classificationsBackend ?>' />
        </div>
        <div class="input-field col l6">
            <p>Topic Tags</p>
            <div id="tourist-tags"></div>
            <input type="hidden" name="topicTags" value='<?= $assignedTagsBackend ?>' />
            <input type="hidden" id="tagsBackend" value='<?= $tagsBackend ?>' />
        </div>
    </div>
    <div>
        <p>Description</p>
        <input type="hidden" name="descriptionwysiwyg" value='<?= $result['descriptionwysiwyg'];?>'/>
        <input type="hidden" name="description" value='<?= $result['description'];?>'/>
        <div id="description-editor">&nbsp;</div>
    </div>
    <div>
        <p>Commuter's Guide</p>
        <input type="hidden" name="commuterguidewysiwyg" value='<?= $result['commuterguidewysiwyg'];?>'/>
        <input type="hidden" name="commuterguide" value='<?= $result['commuterguide'];?>'/>
        <div id="commuterGuide">&nbsp;</div>
    </div>
    <div class="file-field input-field">
      <div class="btn indigo darken-4">
        <span>image</span>
        <input type="file" name="image" accept="image/*">
        <input type="hidden" name="imagebackend" value="<?= $result['imageName']?>"/>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div style="margin-top: 20px;" class="right">
        <button class="btn waves-effect waves-light" type="submit">update<i class="material-icons left">edit</i></button>
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').formSelect();

        $("#tourist-classification").chips({
            placeholder: 'Classification',
            secondaryPlaceholder: 'Classification',
            data: <?= $assignedClassifications ?>,
            autocompleteOptions: {
                data: <?= $classifications ?>
            },
            onChipAdd: function(e, chip) {
                let rawData = $("#classificationsBackend").val();
                let data = JSON.parse(rawData);
                let classifications = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    classifications.push(result[0]);
                }
                $("[name=classifications]").val(JSON.stringify(classifications));
            },
            onChipDelete: function(e, chip) {
                let rawData = $("#classificationsBackend").val();
                let data = JSON.parse(rawData);
                let classifications = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    classifications.push(result[0]);
                }
                $("[name=classifications]").val(JSON.stringify(classifications));
            }
        });

        $("#tourist-tags").chips({
            placeholder: 'Topic Tags',
            secondaryPlaceholder: 'Topic Tags',
            data: <?= $assignedTags ?>,
            autocompleteOptions: {
                data: <?= $tags ?>
            },
            onChipAdd: function(e, chip) {
                let rawData = $("#tagsBackend").val();
                let data = JSON.parse(rawData);
                let tags = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    tags.push(result[0]);
                }
                $("[name=topicTags]").val(JSON.stringify(tags));
            },
            onChipDelete: function(e, chip) {
                let rawData = $("#tagsBackend").val();
                let data = JSON.parse(rawData);
                let tags = [];
                for (let chip of this.chipsData) {
                    let result = data.filter(entry => chip.tag == entry.name).map(entry => entry.id);
                    tags.push(result[0]);
                }
                $("[name=topicTags]").val(JSON.stringify(tags));
            }
        });

        var descriptionField = new Quill('#description-editor', {
            theme: 'snow',
            modules: {
                toolbar: [
                    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                    ['bold', 'italic', 'underline'],
                    ['blockquote'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    [{ 'script': 'sub'}, { 'script': 'super' }],
                    [{ 'indent': '-1'}, { 'indent': '+1' }],
                    [{ 'color': [] }, { 'background': [] }],
                    [{ 'align': [] }],
                    ['link', 'clean']
                ]
            },
            placeholder: 'Compose a descriptive text about the location...'
        });
        descriptionField.setContents(<?= $result['descriptionwysiwyg'] ?>);
        descriptionField.on('text-change', function() {
            $("[name=descriptionwysiwyg]").val(JSON.stringify(descriptionField.getContents()));
            $("[name=description]").val(descriptionField.getText().trim());
        });

        var commuterGuideField = new Quill('#commuterGuide', {
            theme: 'snow',
            modules: {
                toolbar: [
                    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                    ['bold', 'italic', 'underline'],
                    ['blockquote'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    [{ 'script': 'sub'}, { 'script': 'super' }],
                    [{ 'indent': '-1'}, { 'indent': '+1' }],
                    [{ 'color': [] }, { 'background': [] }],
                    [{ 'align': [] }],
                    ['link', 'clean']
                ]
            },
            placeholder: 'Compose a guide on how to travel on this location...'
        });
        commuterGuideField.setContents(<?= $result['commuterguidewysiwyg'] ?>);
        commuterGuideField.on('text-change', function() {
            $("[name=commuterguidewysiwyg]").val(JSON.stringify(commuterGuideField.getContents()));
            $("[name=commuterguide]").val(commuterGuideField.getText().trim());
        });
    });
</script>