<h2>Tourist Destinations</h2>
<a class="waves-light btn-large" href="/cpanel/poi/add"><i class="material-icons left">create</i>Create</a>
<table>
    <thead>
        <tr>
            <th style="width: 35%;">Name</th>
            <th style="width: 30%;">Location</th>
            <th style="width: 15%;">Tourism Circuit</th>
            <th style="width: 20%;">Town</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($poiList as $poi) : ?>
            <tr>
                <td><a href="<?= "/cpanel/poi/{$poi['id']}" ?>"><?= $poi['name'] ?></a></td>
                <td>
                    <?= $poi['address'] ?>
                    <br />
                    Coordinates: <?= $poi['latitude'] ?>, <?= $poi['longitude'] ?>
                </td>
                <td><?= $poi['tourismCircuit'] ?></td>
                <td><?= $poi['town'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
        <?php if (isset($notification)) : ?>
            M.toast({
                html: '<?= $notification ?>'
            });
        <?php endif; ?>
    });
</script>