<a class="waves-effect waves-light btn" href="<?= "/cpanel/poi/{$id}/edit" ?>"><i class="material-icons left">edit</i>edit</a>
<table class="striped" style="margin-top: 10px;">
    <tbody>
        <tr>
            <th style="width: 25%">Name</th>
            <td><?= $result['name']; ?></td>
        </tr>
        <tr>
            <th>Images</th>
            <td>
                <?php if (is_null($result['imageName']) || strlen($result['imageName']) == 0) : ?>
                    <strong>No Image Yet</strong>
                <?php else : ?>
                    <ul class="browser-default">
                        <li>
                            <a href="<?= $imageSrc; ?>" target="_blank" class="collection-item">Primary Image</a>
                        </li>
                        <?php $count = 1; foreach ($images as $image) : ?>
                            <li>
                                <a href="<?= $image ?>" target="_blank" class="collection-item"><?= "Image #{$count}"?></a>
                            </li>
                        <?php $count++; endforeach; ?>
                    </ul>
                    <span style="display: block;">Photo Credit: <?= strlen(trim($result['photoCredit'])) == 0 ? "Not Available" : $result['photoCredit'] ?></span>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th>Augmented Reality Link</th>
            <td>
                <span style="display: block;">Enabled: <?= $result['arEnabled'] == 0 ? "No" : "Yes" ?></span>
                <?php if(strlen(trim($result['arLink'])) == 0): ?>
                    <strong>No Link Yet</strong>
                <?php else: ?>
                    <a href="<?= $result['arLink'] ?>">Link Source</a>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th>Video</th>
            <td>
                <?php if(strlen(trim($result['videoLink'])) == 0): ?>
                    <strong>No Video Yet</strong>
                <?php else: ?>
                    <a href="<?= $result['videoLink']?>" target="_blank">Video Source</a>
                    <span style="display: block;">Video Credit: <?= strlen(trim($result['videoCredit'])) == 0 ? "Not Available" : $result['videoCredit'] ?></span>
                <?php endif;?>
            </td>
        </tr>
        <tr>
            <th>Tourism Circuit</th>
            <td><?= $result['tourismCircuit']; ?></td>
        </tr>
        <tr>
            <th>Town</th>
            <td><?= $result['town']; ?></td>
        </tr>
        <tr>
            <th>Location</th>
            <td>
                <?= $result['address']; ?>
                <br />
                <?= "Latitude: {$result['latitude']}" ?>
                <br />
                <?= "Longitude: {$result['longitude']}" ?>
            </td>
        </tr>
        <tr>
            <th>Level of Development</th>
            <td><?= $result['developmentLevel'] ?></td>
        </tr>
        <tr>
            <th>Classifications</th>
            <td>
                <?php foreach ($result['classifications'] as $classification) : ?>
                    <div class="chip blue lighten-2"><?= $classification['name'] ?></div>
                <?php endforeach; ?>
            </td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>
                <?php foreach ($result['topicTags'] as $tag) : ?>
                    <div class="chip red lighten-2"><?= $tag['name'] ?></div>
                <?php endforeach; ?>
            </td>
        </tr>
        <tr>
            <th>Description</th>
            <td>
                <div id="description" style="width: 100%"></div>
            </td>
        </tr>
        <tr>
            <th>Commuter's Guide</th>
            <td>
                <div id="commuterGuide" style="width: 100%"></div>
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        let descriptionView = new Quill('#description', {
            theme: 'bubble'
        })
        descriptionView.disable();
        descriptionView.setContents(<?= $result['descriptionwysiwyg']; ?>);

        let commuterGuideView = new Quill('#commuterGuide', {
            theme: 'bubble'
        })
        commuterGuideView.disable();
        commuterGuideView.setContents(<?= $result['commuterguidewysiwyg']; ?>);
    });
</script>