<div class="section">
    <h5>Manage Schedules</h5>
</div>
<form method="post" action=<?= $formUrl ?>>
    <div class="input-field">
        <input name="name" type="text" class="validate" readonly value="<?=$name?>"/>
        <label>Name</label>
    </div>
</form>
<table class="striped">
    <thead>
        <tr>
            <th style="width: 20%">Day</th>
            <th style="width: 20%">Operating Hours</th>
            <th style="width: 50%">Notes</th>
            <th style="width: 10%">Actions</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>