<div class="section">
    <h5>Manage Schedules</h5>
</div>
<a class="waves-light btn-large" href="/cpanel/poi/<?= $id ?>/schedule"><i class="material-icons left">create</i>Create</a>
<table class="striped">
    <thead>
        <tr>
            <th>Name</th>
            <td colspan="3"><?= $name ?></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th style="width: 20%">Day</th>
            <th style="width: 20%">Operating Hours</th>
            <th style="width: 50%">Notes</th>
            <th style="width: 10%">Actions</th>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
        <?php if (isset($notification)) : ?>
            M.toast({
                html: '<?= $notification ?>'
            });
        <?php endif; ?>
    });
</script>